// examples/vue/src/components/Ideogram.vue
<template>
  <div id="ideo-container"></div>
</template>

<script>
  import Ideogram from 'ideogram'

  export default {
    name: 'Ideogram',
    mounted: function () {
      return new Ideogram({
        organism: 'human',
        container: '#ideo-container',
        dataDir: 'https://cdn.jsdelivr.net/npm/ideogram@1.20.0/dist/data/bands/native/'
      })
    }
  }
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
  #ideo-container {
    height: 300px;
    width: 50%;
    margin: auto;
  }
</style>

// examples/angular/src/app/ideogram/ideogram.component.ts
import { Component, OnInit} from '@angular/core';
import Ideogram from 'ideogram';

@Component({
  selector: 'app-ideogram',
  templateUrl: './ideogram.component.html',
  styleUrls: ['./ideogram.component.css']
})
export class IdeogramComponent implements OnInit {

  constructor() { }

  ngOnInit() {
    this.createIdeogram();
  }

  createIdeogram() {
    const ideogram = new Ideogram({
      organism: 'human',
      dataDir: 'https://unpkg.com/ideogram@0.10.0/dist/data/bands/native/',
      container: '#ideo-container'
    });
  }

}

<div id="ideo-container"></div>
